# -*- coding: utf-8 -*-
"""code challenge

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QaYCuZkl55rOzD2SqeiPqpkU2fZ4a1S6
"""

import pandas as pd
from google.colab import files
uploaded = files.upload()
import matplotlib.pyplot as plt
import csv

x=[]
y=[]

with open('a01_3.csv', 'r') as csvfile:
    plots= csv.reader(csvfile, delimiter=',')
    for row in plots:
        x.append((row[0]))
        y.append((row[1]))


plt.plot(x,y, marker='o')

plt.title('ECG Signal')

plt.xlabel('Time')
plt.ylabel('Raw_ECG')

plt.show()
